# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1447333905);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1447334025);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1447333545);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1447333785);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1447333665);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151104111905");
user_pref("browser.slowStartup.averageTime", 1119);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20151104111905");
user_pref("browser.startup.homepage_override.mstone", "38.4.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1447419825161");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1447333485923");
user_pref("datareporting.policy.firstRunTime", "1447333425160");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 921);
user_pref("datareporting.sessions.current.main", 80);
user_pref("datareporting.sessions.current.sessionRestored", 1017);
user_pref("datareporting.sessions.current.startTime", "1447334157487");
user_pref("datareporting.sessions.current.totalTime", 71);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1447333424643,\"a\":8,\"t\":729,\"c\":true,\"m\":80,\"fp\":1124,\"sr\":1258}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"38.4.0\",\"type\":\"locale\",\"descriptor\":\"/home/controls/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.4.0");
user_pref("extensions.lastPlatformVersion", "38.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-system-user\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/home/controls/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.4.0\",\"st\":1446659752000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.4.0\",\"st\":1447330313000,\"mt\":1446659646000}}}");
user_pref("gecko.buildID", "20151104111905");
user_pref("gecko.mstone", "38.4.0");
user_pref("idle.lastDailyNotification", 1447333653);
user_pref("media.gmp-manager.buildID", "20151104111905");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1447333653);
user_pref("places.history.expiration.transient_current_max_pages", 102891);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1447333653);
user_pref("toolkit.startup.last_success", 1447334157);
user_pref("toolkit.telemetry.previousBuildID", "20151104111905");
